-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 09:20:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Projet_WEB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projet_WEB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projet_WEB` DEFAULT CHARACTER SET utf8 ;
USE `Projet_WEB` ;

-- -----------------------------------------------------
-- Table `Projet_WEB`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`companies` (
  `id_companies` INT NOT NULL AUTO_INCREMENT,
  `name_company` VARCHAR(45) NULL,
  `logo_company` VARCHAR(255) NULL,
  `city_companie` VARCHAR(45) NOT NULL,
  `adress_company` VARCHAR(45) NOT NULL,
  `contact_company` VARCHAR(45) NOT NULL,
  `staff_number` INT NOT NULL,
  `description_company` VARCHAR(255) NOT NULL,
  `cre_companies` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_companies` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_companies` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_companies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`areas` (
  `id_areas` INT NOT NULL AUTO_INCREMENT,
  `name_area` VARCHAR(45) NOT NULL,
  `cre_areas` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_areas` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_areas` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_areas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`expertises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`expertises` (
  `id_expertises` INT NOT NULL AUTO_INCREMENT,
  `name_expertise` VARCHAR(45) NOT NULL,
  `cre_expertises` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_expertises` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_expertises` TIMESTAMP NULL DEFAULT NULL,
  `areas_id_areas` INT NOT NULL,
  INDEX `fk_expertises_areas1_idx` (`areas_id_areas` ASC) VISIBLE,
  PRIMARY KEY (`id_expertises`),
  CONSTRAINT `fk_expertises_areas1`
    FOREIGN KEY (`areas_id_areas`)
    REFERENCES `Projet_WEB`.`areas` (`id_areas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`addresses` (
  `id_addresses` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number_street` VARCHAR(45) NULL,
  `country` VARCHAR(45) NOT NULL,
  `postal_code` INT NULL,
  `other` VARCHAR(255) NULL,
  `cre_addresses` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_addresses` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_addresses` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_addresses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`offers` (
  `id_offers` INT NOT NULL,
  `contact_offer` VARCHAR(45) NULL,
  `duration` INT NULL,
  `link_offer` VARCHAR(45) NULL,
  `description_offer` VARCHAR(255) NULL,
  `type_offer` VARCHAR(45) NOT NULL,
  `date_offer` DATE NOT NULL,
  `name_offer` VARCHAR(45) NOT NULL,
  `cre_offers` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_offers` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `salary` VARCHAR(45) NOT NULL,
  `del_offers` TIMESTAMP NULL DEFAULT NULL,
  `number_offer` VARCHAR(45) NULL,
  `expertises_id_expertises` INT NOT NULL,
  `companies_id_companies` INT NOT NULL,
  `adresses_id_adresses` INT NOT NULL,
  `level_offer` INT NOT NULL,
  PRIMARY KEY (`id_offers`),
  INDEX `fk_Offres_Entreprises1_idx` (`companies_id_companies` ASC) VISIBLE,
  INDEX `fk_offers_expertises1_idx` (`expertises_id_expertises` ASC) VISIBLE,
  INDEX `fk_offers_adresses1_idx` (`adresses_id_adresses` ASC) VISIBLE,
  CONSTRAINT `fk_Offres_Entreprises1`
    FOREIGN KEY (`companies_id_companies`)
    REFERENCES `Projet_WEB`.`companies` (`id_companies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offers_expertises1`
    FOREIGN KEY (`expertises_id_expertises`)
    REFERENCES `Projet_WEB`.`expertises` (`id_expertises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offers_adresses1`
    FOREIGN KEY (`adresses_id_adresses`)
    REFERENCES `Projet_WEB`.`addresses` (`id_addresses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`roles` (
  `id_roles` INT NOT NULL AUTO_INCREMENT,
  `name_role` VARCHAR(45) NULL,
  `cre_roles` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_roles` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_roles` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_roles`),
  UNIQUE INDEX `Nom_role_UNIQUE` (`name_role` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(70) NOT NULL,
  `last_name` VARCHAR(70) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `birth_date` DATE NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `graduation_year` INT NULL,
  `profile_picture` VARCHAR(255) NULL,
  `cre_users` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_users` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_users` TIMESTAMP NULL DEFAULT NULL,
  `roles_id_roles` INT NULL,
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Users_Roles1_idx` (`roles_id_roles` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Roles1`
    FOREIGN KEY (`roles_id_roles`)
    REFERENCES `Projet_WEB`.`roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`campus` (
  `id_campus` INT NOT NULL AUTO_INCREMENT,
  `name_campus` VARCHAR(45) NULL,
  `cre_campus` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_campus` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_campus` TIMESTAMP NULL DEFAULT NULL,
  `addresses_id_addresses` INT NOT NULL,
  PRIMARY KEY (`id_campus`),
  UNIQUE INDEX `Ville_UNIQUE` (`name_campus` ASC) VISIBLE,
  INDEX `fk_campus_adresses1_idx` (`addresses_id_addresses` ASC) VISIBLE,
  CONSTRAINT `fk_campus_adresses1`
    FOREIGN KEY (`addresses_id_addresses`)
    REFERENCES `Projet_WEB`.`addresses` (`id_addresses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`wishlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`wishlists` (
  `users_id_users` INT NOT NULL,
  `offers_id_offers` INT NOT NULL,
  `cre_wishlists` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_wishlists` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_wishlists` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`users_id_users`, `offers_id_offers`),
  INDEX `fk_Users_has_Offres_Offres1_idx` (`offers_id_offers` ASC) VISIBLE,
  INDEX `fk_Users_has_Offres_Users1_idx` (`users_id_users` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Offres_Users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `Projet_WEB`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Offres_Offres1`
    FOREIGN KEY (`offers_id_offers`)
    REFERENCES `Projet_WEB`.`offers` (`id_offers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`ratings` (
  `users_id_users` INT NOT NULL,
  `companies_id_companies` INT NOT NULL,
  `rating` INT NULL,
  `cre_ratings` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_ratings` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_ratings` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`users_id_users`, `companies_id_companies`),
  INDEX `fk_Users_has_Entreprises_Entreprises1_idx` (`companies_id_companies` ASC) VISIBLE,
  INDEX `fk_Users_has_Entreprises_Users1_idx` (`users_id_users` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Entreprises_Users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `Projet_WEB`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Entreprises_Entreprises1`
    FOREIGN KEY (`companies_id_companies`)
    REFERENCES `Projet_WEB`.`companies` (`id_companies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`companies_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`companies_areas` (
  `companies_id_companies` INT NOT NULL,
  `areas_id_areas` INT NOT NULL,
  `cre_companies_areas` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_companies_areas` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_companies_areas` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`companies_id_companies`, `areas_id_areas`),
  INDEX `fk_Entreprises_has_Domaine_Domaine1_idx` (`areas_id_areas` ASC) VISIBLE,
  INDEX `fk_Entreprises_has_Domaine_Entreprises1_idx` (`companies_id_companies` ASC) VISIBLE,
  CONSTRAINT `fk_Entreprises_has_Domaine_Entreprises1`
    FOREIGN KEY (`companies_id_companies`)
    REFERENCES `Projet_WEB`.`companies` (`id_companies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entreprises_has_Domaine_Domaine1`
    FOREIGN KEY (`areas_id_areas`)
    REFERENCES `Projet_WEB`.`areas` (`id_areas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`classes` (
  `id_classes` INT NOT NULL AUTO_INCREMENT,
  `name_class` VARCHAR(45) NOT NULL,
  `cre_classes` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_classes` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_classes` TIMESTAMP NULL DEFAULT NULL,
  `campus_id_campus` INT NOT NULL,
  PRIMARY KEY (`id_classes`),
  INDEX `fk_class_campus1_idx` (`campus_id_campus` ASC) VISIBLE,
  CONSTRAINT `fk_class_campus1`
    FOREIGN KEY (`campus_id_campus`)
    REFERENCES `Projet_WEB`.`campus` (`id_campus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`users_in_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`users_in_classes` (
  `classes_id_classes` INT NOT NULL,
  `users_id_users` INT NOT NULL,
  `cre_users_in_classes` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_users_in_classes` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_users_in_classes` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`classes_id_classes`, `users_id_users`),
  INDEX `fk_classes_has_users_users1_idx` (`users_id_users` ASC) VISIBLE,
  INDEX `fk_classes_has_users_classes1_idx` (`classes_id_classes` ASC) VISIBLE,
  CONSTRAINT `fk_classes_has_users_classes1`
    FOREIGN KEY (`classes_id_classes`)
    REFERENCES `Projet_WEB`.`classes` (`id_classes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_users_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `Projet_WEB`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`applications` (
  `idapplications` INT NOT NULL AUTO_INCREMENT,
  `offers_id_offers` INT NOT NULL,
  `users_id_users` INT NOT NULL,
  `cre_applications` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_applications` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_applications` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idapplications`),
  INDEX `fk_applications_offers1_idx` (`offers_id_offers` ASC) VISIBLE,
  INDEX `fk_applications_users1_idx` (`users_id_users` ASC) VISIBLE,
  CONSTRAINT `fk_applications_offers1`
    FOREIGN KEY (`offers_id_offers`)
    REFERENCES `Projet_WEB`.`offers` (`id_offers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applications_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `Projet_WEB`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_WEB`.`companies_addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_WEB`.`companies_addresses` (
  `companies_id_companies` INT NOT NULL,
  `addresses_id_addresses` INT NOT NULL,
  `cre_companies_addresses` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mod_companies_addresses` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_companies_addresses` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`companies_id_companies`, `addresses_id_addresses`),
  INDEX `fk_companies_has_adresses_adresses1_idx` (`addresses_id_addresses` ASC) VISIBLE,
  INDEX `fk_companies_has_adresses_companies1_idx` (`companies_id_companies` ASC) VISIBLE,
  CONSTRAINT `fk_companies_has_adresses_companies1`
    FOREIGN KEY (`companies_id_companies`)
    REFERENCES `Projet_WEB`.`companies` (`id_companies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_adresses_adresses1`
    FOREIGN KEY (`addresses_id_addresses`)
    REFERENCES `Projet_WEB`.`addresses` (`id_addresses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
